import type { Potion, AlchemyIngredient } from "./types";

export const POTIONS_LIST: Potion[] = [
    {
        id: 'potion-minor-healing',
        name: 'Малое зелье лечения',
        note: 'Слабое зелье, восстанавливающее небольшое количество здоровья.',
        effects: [{ stat: 'hp', value: 25 }],
        tier: 'обычный',
        image: 'https://i.postimg.cc/9M3R0zB5/image.png',
        quantity: 1,
        inventoryTag: 'зелья',
    },
    {
        id: 'potion-medium-healing',
        name: 'Среднее зелье лечения',
        note: 'Более сильное зелье, восстанавливающее значительное количество здоровья.',
        effects: [{ stat: 'hp', value: 75 }],
        tier: 'обычный',
        image: 'https://i.postimg.cc/9M3R0zB5/image.png',
        quantity: 1,
        inventoryTag: 'зелья',
    },
    {
        id: 'potion-greater-healing',
        name: 'Большое зелье лечения',
        note: 'Очень мощное зелье, способное почти полностью восстановить здоровье.',
        effects: [{ stat: 'hp', value: 150 }],
        tier: 'редкий',
        image: 'https://i.postimg.cc/9M3R0zB5/image.png',
        quantity: 1,
        inventoryTag: 'зелья',
    },
    {
        id: 'potion-minor-mana',
        name: 'Малое зелье маны',
        note: 'Слабое зелье, восстанавливающее небольшое количество маны.',
        effects: [{ stat: 'mana', value: 25 }],
        tier: 'обычный',
        image: 'https://i.postimg.cc/0j3SkK1R/image.png',
        quantity: 1,
        inventoryTag: 'зелья',
    },
    {
        id: 'potion-luck',
        name: 'Зелье удачи',
        note: 'Временно повышает удачу выпившего.',
        effects: [{ stat: 'luck', value: 10, durationSec: 3600 }],
        tier: 'редкий',
        image: 'https://i.postimg.cc/44D3vDkS/image.png',
        quantity: 1,
        inventoryTag: 'зелья',
    },
     {
        id: 'potion-anti-cold',
        name: 'Антипростудное зелье «Вылечись сегодня»',
        note: 'Быстро излечивает от обычной простуды.',
        effects: [],
        tier: 'обычный',
        image: 'https://i.postimg.cc/0j3SkK1R/image.png',
        quantity: 1,
        inventoryTag: 'зелья',
    },
];

export const INGREDIENTS_LIST: AlchemyIngredient[] = [];
